### ISSUE TITLE
/settings/accountに行ってブラウザの戻るボタン押しても、戻れない

### ISSUE THREAD

**Issue by sasakiyudai** [RIFT-tokyo/transcendence-front#38]
/settings/accountに行ってブラウザの戻るボタン押しても、戻れない

**Comment by tkomatsu** [comment]
これは戻れないというより、
`/settings`に飛ぶと、`/settings/account`に自動で遷移するので、1回戻るだけだと`/settings`に行くだけなのですぐに`/settings/account`に遷移して戻っていないように見えるという罠なのです。
同じように
```ts
<Route path="path">
  <Route index element={<Navigate to="subpath" />} />
  <Route path="subpath" element={<SomeComponents />} />
</Route>
```
になる部分があると同じ感じになります。
indexのときの扱いをどうしたらいいかがいまいちわかっておらず、、、、って感じですね。
