### ISSUE TITLE
footerの縦幅を狭くする

### ISSUE THREAD

**Issue by nafuka11** [RIFT-tokyo/transcendence-front#68]
## 目的
footerのheightは現在72pxとなっており、固定すると画面が狭く感じられる。
このため、TRANSCENDENCEのロゴを消すことで、footerのheightを狭くする。

**Comment by tkomatsu** [comment]
`App icon by icons8, © 2022 RIFT Tokyo` だけでも良いかも？

**Comment by nafuka11** [comment]
良さそうですね！
変更を加えてみました。こちらの方がスッキリして見えますね。
![2022-05-07 15-54-13](https://user-images.githubusercontent.com/42476527/167242767-ffcffb5b-ca59-4c48-9d84-5279cc3a86f9.png)
これで問題なさそうなら、この方向で行こうと思います。

ちなみに変更前は以下のような感じです。
![2022-05-07 15-29-20](https://user-images.githubusercontent.com/42476527/167242874-8e675a19-1201-41c4-8d9e-ad02f83143e9.png)

**Comment by nafuka11** [comment]
Discordで話題に上がった、「AppBarとFooterを除いた高さ出すやつを定数としてconfigに」も対応いたします。
